version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: imsc_ims_connect
      MYSQL_USER: imsc_root
      MYSQL_PASSWORD: 1212
      MYSQL_ROOT_PASSWORD: new_root_password
    ports:
      - "3307:3306"

  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8801
    volumes:
      - .:/app
    ports:
      - "8801:8801"
    depends_on:
      - db
    environment:
      - DB_NAME=imsc_ims_connect
      - DB_USER=imsc_root
      - DB_PASSWORD=1212
      - DB_HOST=db
      - DB_PORT=3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: new_root_password
    ports:
      - "8080:80"
    depends_on:
      - db