version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"  # Change the host port to 3307

  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8801
    volumes:
      - .:/app
    ports:
      - "8801:8801"
    depends_on:
      - db
    environment:
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306